"""initial schema.

Revision ID: 31b8b866d80e
Revises:
Create Date: 2026-04-16 15:32:39.593022
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "31b8b866d80e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("wikidata_qid", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("country", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cities_wikidata_qid"), "cities", ["wikidata_qid"], unique=True)
    op.create_table(
        "refresh_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("last_refresh_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_refresh_museums_count", sa.Integer(), nullable=True),
        sa.Column("last_refresh_cities_count", sa.Integer(), nullable=True),
        sa.CheckConstraint("id = 1", name="ck_refresh_state_singleton"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "museums",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("wikidata_qid", sa.String(length=20), nullable=True),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("wikipedia_title", sa.String(length=300), nullable=False),
        sa.Column("city_id", sa.Integer(), nullable=True),
        sa.Column("country", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["city_id"], ["cities.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_museums_city_id"), "museums", ["city_id"], unique=False)
    op.create_index(op.f("ix_museums_wikidata_qid"), "museums", ["wikidata_qid"], unique=True)
    op.create_table(
        "population_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("population", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("population > 0", name="ck_population_records_population_positive"),
        sa.CheckConstraint("year >= 2000 AND year <= 2100", name="ck_population_records_year_range"),
        sa.ForeignKeyConstraint(["city_id"], ["cities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("city_id", "year", name="uq_population_records_city_year"),
    )
    op.create_index(op.f("ix_population_records_city_id"), "population_records", ["city_id"], unique=False)
    op.create_table(
        "visitor_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("museum_id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("visitors", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("visitors > 0", name="ck_visitor_records_visitors_positive"),
        sa.CheckConstraint("year >= 2000 AND year <= 2100", name="ck_visitor_records_year_range"),
        sa.ForeignKeyConstraint(["museum_id"], ["museums.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("museum_id", "year", name="uq_visitor_records_museum_year"),
    )
    op.create_index(op.f("ix_visitor_records_museum_id"), "visitor_records", ["museum_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_visitor_records_museum_id"), table_name="visitor_records")
    op.drop_table("visitor_records")
    op.drop_index(op.f("ix_population_records_city_id"), table_name="population_records")
    op.drop_table("population_records")
    op.drop_index(op.f("ix_museums_wikidata_qid"), table_name="museums")
    op.drop_index(op.f("ix_museums_city_id"), table_name="museums")
    op.drop_table("museums")
    op.drop_table("refresh_state")
    op.drop_index(op.f("ix_cities_wikidata_qid"), table_name="cities")
    op.drop_table("cities")
    # ### end Alembic commands ###
